# -*- coding: utf-8 -*-
"""Learning Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqnGVWPeSOUDDI2PWwwUeHbWwrOEgPtY
"""

import pandas as pd

df = pd.DataFrame({
    "product":  ["apples", "bananas", "grapes", "berries"],
    "quantity": [367, 421, 569, 234],
    "price":    [0.5, 0.75, 0.1, 0.09,]
})
df

df.shape

df.dtypes

df.describe()

df["total"] = df["quantity"] * df["price"]
df

df[df["quantity"] > 400]

df = pd.DataFrame({
    "product":  ["apples", "bananas", "grapes", "berries", "dragon fruit", "oranges", "apples"],
    "quantity": [367, 421, 569, 234, 67, 132, 264],
    "price":    [0.5, 0.75, 0.1, 0.09, 2.1, 0.4, 0.345]
})
df

df.groupby("product")["quantity"].sum()

df.groupby("product")["quantity"].mean()

df.to_csv("fruits.csv", index=False)

